### ISSUE TITLE
[fix] Uso de RaisedButton descontinuado no feed_tags_filter.dart

### ISSUE THREAD

**Issue by shonorio** [institutoazmina/penhas-app#239]
Problemas encontrados durante a análise do código com o Flutter Analyzer no arquivo `feed_tags_filter.dart`:

1. **Uso de `RaisedButton` Descontinuado**:
   O widget `RaisedButton` foi descontinuado e não deve mais ser utilizado. A recomendação é substituir o uso de `RaisedButton` por `PenhasButton`.
   - **Arquivo**: `lib/app/features/feed/presentation/pages/feed_tags_filter.dart`

### Passos a seguir:
- Substituir todos os usos de `RaisedButton` por `PenhasButton` no arquivo mencionado.

**Comment by RoxyRoses** [comment]
O PenhasButton.roundedOutlined nao possui a borda roxa igual o botao anterior, sera necessario adicionar um estilo ou um botao que possua a borda roxa:

![Screenshot_1735220114](https://github.com/user-attachments/assets/56c762e6-8a17-46b2-a68f-9c8f5566c3f6)
![Screenshot_1735220136](https://github.com/user-attachments/assets/f40d2866-4b48-45ad-b58f-dce986a6740f)
