### ISSUE TITLE
[fix] Uso de RaisedButton descontinuado no feed_category_filter.dart

### ISSUE THREAD

**Issue by shonorio** [institutoazmina/penhas-app#240]
Problemas encontrados durante a análise do código com o Flutter Analyzer no arquivo `feed_category_filter.dart`:

1. **Uso de `RaisedButton` Descontinuado**:
   O widget `RaisedButton` foi descontinuado e não deve mais ser utilizado. A recomendação é substituir o uso de `RaisedButton` por `PenhasButton`.
   - **Arquivo**: `lib/app/features/feed/presentation/pages/feed_category_filter.dart`

### Passos a seguir:
- Substituir todos os usos de `RaisedButton` por `PenhasButton` no arquivo mencionado.

**Comment by RoxyRoses** [comment]
O PenhasButton.roundedOutlined nao possui a borda roxa igual o botao anterior, sera necessario adicionar um estilo ou um botao que possua a borda roxa: 

![Screenshot_1735219396](https://github.com/user-attachments/assets/d30ec598-1c23-47ab-b126-e4d7725416dd)
![Screenshot_1735219409](https://github.com/user-attachments/assets/07642e61-a17d-4d99-b217-9a01f8ef25a2)
